### ISSUE TITLE
Design new spinner

### ISSUE THREAD

**Issue by kevinsawicki** [play/play-android#1]
Need a new spinner for when things are loading.

The only idea I had would be a top-down view of a spinning CD, old school.

**Comment by mattgraham** [comment]
Here is the cd: 
![image](http://f.cl.ly/items/1H0N0Q1l060l2e2o1p2P/Untitled-1.png)

I'm working on what it would look like overlaid on the image, however, do we want to have some text that randomly says
- Spinning it up
- Searching the jukebox
- Loading the Album

etc. ? @kevinsawicki

**Comment by kevinsawicki** [comment]
we can definitely have text below, above, next to it when loading.

**Comment by kevinsawicki** [comment]
I've checked this in, updates can be made [here](https://github.com/play/play-android/blob/master/app/res/drawable/spinner.png).
