### ISSUE TITLE
Search result > Select Album

### ISSUE THREAD

**Issue by mattgraham** [play/play-android#3]
After searching for an artist I'd like to see albums and songs separate so you can select the entire album or individual songs. This is a quick mockup but I think there is value in being able to que up an entire album: 

![image](http://f.cl.ly/items/2S252p2v3l2z0e3Y2M2N/android-play%20copy.png)

**Comment by kevinsawicki** [comment]
I love this, I've been struggling with how to best queue up albums instead of songs and this does it.
