### ISSUE TITLE
Queue album doesn't detect dupes

### ISSUE THREAD

**Issue by anaisbetts** [play/play-android#5]
If somebody uploads the same album twice, Play isn't smart enough to de-dup them. When you queue up albums, sort them by track # then remove dupes before you start hitting the Queue Track API

**Comment by kevinsawicki** [comment]
Songs have track numbers?

**Comment by kevinsawicki** [comment]
The hacky queueing that the Android app does was just a stop gap until something like [this](https://github.com/play/play/pull/188) is available from the API.

**Comment by anaisbetts** [comment]
Hm, I could've sworn I wrote code to do this in the client but now I'm not seeing it. :poop:
